services:
  ros2_jazzy_teleop:
    image: ros2_jazzy_teleop
    ports:
      - "22:22"
    devices:
      - "/dev/input/js0:/dev/input/js0"
    volumes:
      #placeholder for pseudoterminal path - run detect_pty.sh
      - "/dev/pts/1:/dev/ttyACM0"
    command: ros2 launch robotont_driver driver_launch.py device_name:='/dev/ttyACM0'